# Generated by Django 3.1.7 on 2021-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
