# Generated by Django 3.1.7 on 2021-03-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0003_auto_20210301_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='payment_date',
            new_name='payment_time',
        ),
    ]
