# Generated by Django 3.1.7 on 2021-03-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0004_auto_20210301_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
